Help: technical info & images
delta-cs/seminar-domjudge pull request #27
Opened 2023-07-28 20:42 UTC by matous-volf

![localhost_12345_public_help](https://github.com/delta-cs/seminar-domjudge/assets/66163112/66f9abee-a582-4687-abe2-b02eeeaf0282)

2023-07-28 20:54 UTC, matous-volf commented
jeste me napada, chceme v tlacitku na napovedu zobrazovat text cesky (jak to funguje)? neni to soucast rozhrani a tedy pouzit anglictinu?

2023-07-29 07:07 UTC, zapotocnylubos requested changes

2023-07-29 07:07 UTC, zapotocnylubos commented on webapp/templates/base.html.twig
> +    <link rel="stylesheet" href="{{ asset("css/help.css") }}">
toto je potreba pouze na help strance ne? -> tady se to bude includovat vsude

2023-07-29 07:07 UTC, zapotocnylubos commented on webapp/templates/base.html.twig
> +    <link rel="stylesheet" href="{{ asset("css/help.css") }}">
castokrat se to dela tak, ze zde v parent zadefinuje sekci, ktera bude prazdna (treba extra_css) a tuto sekci potom v child sablone nadefinujes.

Snad to twig umi - https://stackoverflow.com/questions/32585897/changing-css-selector-for-parent-template-using-twig

2023-07-29 09:08 UTC, zapotocnylubos approved these changes

2023-07-29 09:08 UTC, merged